postgres_host: "postgres"
postgres_port: "5432"
database_name: "postgres"
postgres_username: "postgres"
postgres_password: "postgrespass"
jwt_key: "demokey"
policy_repo: "https://github.com/poonai/inspektor-policy.git"
github_access_token: ""